name: Release

on:
  push:
    branches:
      - main


concurrency:
  group: Production-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Production-${{ matrix.app }}
    strategy:
      fail-fast: false
      matrix:
        app: [a, b, c]
    steps:
      - run: echo ${{ matrix.app }}
