name: Release

on:
  push:
    branches:
      - main


jobs:
  release:
    runs-on: ubuntu-latest
    environment: Production-${{ matrix.app }}    
    concurrency:
      group: Production
    strategy:
      fail-fast: false
      matrix:
        app: [a, b, c]
    steps:
      - run: echo ${{ matrix.app }}
