name: Release

on:
  push:
    branches:
      - main




jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: ${{ github.run_id }}
          github_token: ${{ github.token }}
