name: Release

on:
  push: 
    tags:
      - '*'

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: |
          echo ${GITHUB_REF##*-}
      - name: Show Information
        run: |
          echo '::set-output name=version::${{ github.run_id }}.${{ github.run_attempt }}'
          echo "Name is ${{ github.event.inputs.name }} "
          echo "This workflow run is triggered by ${{ github.event_name }} "
          echo " *****************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo " *****************************************************************************"
      - id: vars
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.branch }}
      - uses: fregante/setup-git-user@v1
      - run: |
          echo "test"
          echo ${GITHUB_REF##*-}
        
