name: Update snapshots
on:
  check_suite:
    types:
      - rerequested
      - completed
      - requested
  check_run:
    types:
      - requested_action
      - completed
      - created
      - rerequested
jobs:
  update-snapshots:
    if: ${{ github.event.requested_action.identifier == 'update-snapshots' }}
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.branch }}
      - uses: fregante/setup-git-user@v1
      - run: echo "test"
